module.exports={
    USERS_COLLECTION:"customer",
    PRODUCT_COLLECTION:"product",
    CATEGORY_COLLECTION:"category",
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WALLET_COLLECTION:'wallet',
    COUPON_COLLECTION:'coupon',
    WISH_COLLECTION:'wish',
    BANNER_COLLECTION:'banner'
} 